version: 2

jobs:
  linux-aarch64-release:
    working_directory: ~/linux-aarch64-release
    machine:
      image: ubuntu-2204:current
    # resource_class is what tells CircleCI to use an ARM worker for native arm builds
    #   https://circleci.com/product/features/resource-classes/
    #   https://circleci.com/docs/using-arm/
    resource_class: arm.large
    steps:
      - checkout
      - run:
          name: "Checkout Submodules"
          command: |
            git reset --hard
            git submodule init
            git submodule update
      - run:
          name: Install build dependencies
          command: |
            sudo apt update
            sudo apt install cmake g++ libopenmpi-dev libhdf5-openmpi-dev hdf5-tools python3 python3-setuptools
            python3 -m pip install -U numpy scipy matplotlib
      - run:
          name: Build
          command: |
            cmake -S . -B build \
              -DAMReX_SPACEDIM=1 -DCMAKE_BUILD_TYPE=Release
            cmake --build build --parallel 4
      - run:
          name: Test
          command: |
            ctest --test-dir build --output-on-failure
            
  linux-aarch64-hwasan:
    working_directory: ~/linux-aarch64-hwasan
    machine:
      image: ubuntu-2204:current
    # resource_class is what tells CircleCI to use an ARM worker for native arm builds
    #   https://circleci.com/product/features/resource-classes/
    #   https://circleci.com/docs/using-arm/
    resource_class: arm.large
    steps:
      - checkout
      - run:
          name: "Checkout Submodules"
          command: |
            git reset --hard
            git submodule init
            git submodule update
      - run:
          name: Install build dependencies
          command: |
            sudo apt update
            sudo apt install cmake clang libopenmpi-dev libhdf5-openmpi-dev hdf5-tools python3 python3-setuptools
            python3 -m pip install -U numpy scipy matplotlib
      - run:
          name: Build
          command: |
            cmake -S . -B build \
              -DCMAKE_BUILD_TYPE=Release -DENABLE_HWASAN=ON \
              -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld" \
              -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
              -DAMReX_SPACEDIM=1
            cmake --build build --parallel 4
      - run:
          name: Test
          no_output_timeout: 30m
          command: |
            ctest --test-dir build --output-on-failure

workflows:
  version: 2
  all-tests:
    jobs:
      - linux-aarch64-release
      - linux-aarch64-hwasan
